/* This SPSS program was automatically generated by Stat/Transfer ver.10.1.1866.0714 */

/* ENCODING CP1252 */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME="C:/work/DataversUploads/M163V1/CJUEXP.dat" LRECL=160 .

DATA LIST FILE=DATA/
   caseid 1-5               telephne 6-11            city 12-13            
   county 14-15             ethcode 16 (A)           centract 17-22        
   blktract 23              ethsmple 24              votestat 25           
   zregstat 26              zpartsta 27              contri$ 28            
   polisho 29               poliwork 30              polirali 31           
   partyid 32               toeo 33                  tonews 34             
   togrup 35                yprob 36-37              comprob 38-39         
   religion 40              evanprot 41              protdnom 42-43        
   edu 44                   maristat 45              yngstat 46            
   yng# 47                  yng#edu 48               yngcol 49             
   ernr$ 50                 zernrlin 51-52           empstat 53            
   occu 54                  unemp 55                 umem 56               
   rempstat 57              roccu 58                 runemp 59             
   rumem 60                 hempstat 61              hoccu 62              
   hunemp 63                humem 64                 race 65               
   natnlity 66-67           ethnicid 68              asam 69               
   hispid 70                zusp 71-72               ifracep 73            
   zracep 74-75             psolgov 76               pgovlev 77            
   zpsolgrp 78              ifgrp2 79                zgrp2 80-81           
   zgrp2p 82-83             p2solgov 84              p2govlev 85           
   zp2solgr 86              ifloluc 87               zloluc1 88-89         
   zloluc2 90-91            zloluc3 92-93            zloluc4 94-95         
   ifhiluc 96               zhiluc1 97-98            zhiluc2 99-100        
   zhiluc3 101-102          zhiluc4 103-104          prej 105              
   zprejgrp 106-107         selfprej 108             zsitprej 109-110      
   futprej 111              arms$ 112                era 113               
   edutax 114               prayr 115                welfa$ 116            
   abort$ 117               nogun 118                deathp 119            
   amnesty 120              empsanc 121              bilinge 122           
   bilingb 123              zabort 124               zborn 125-126         
   ifupama 127              zpaborn 128-129          zmaborn 130-131       
   link 132                 link$ 133                setl 134              
   yentry 135-137           ifctzn 138               ustate 139-140 (A)    
   ucal 141                 ulink 142                zlang 143-144         
   votlang 145              yyrborn 146-148          homown 149            
   income 150               pvote 151                voteuse 152           
   sex 153                  coop 154                 info 155              
   tru 156                  imgen 157                noneng 158            
   splang 159               iflang 160 .          

VARIABLE LABELS
   caseid "`CASE IDENTIFICATION NUMBER'"
   blktract 'HIGH PERCENTAGE BLACK TRACT'
   ethsmple 'SAMPLING FRAME'
   votestat "`PARTICIPATE IN 1984 ELECTION'"
   zregstat 'REGISTRATION STATUS IN 1984'
   zpartsta 'PARTY REGISTRATION STATUS OF INDIVI'
   contri$ "`CONTRIBUTE $$ TO POLITICAL UNIT IN 84'"
   polisho "`EXHIBIT STICKER OR POSTER IN 84'"
   poliwork "`POLI WORK ON CAMPAIGN 84'"
   polirali "`ATTENDED POLITICAL RALLY 84'"
   partyid 'MICHIGAN PARTYID'
   toeo "`CMCATE OPINION TO ELECTED OFFICIALS'"
   tonews "`CMCATE OPINION TO NEWSMEDIA'"
   togrup "`WORKED WITH GROUP AGAINST PROBLEM'"
   yprob 'COMMUNITY ORGANIZATION PROBLEM'
   comprob 'TYPE OF COMM. ORG. PROBLEM'
   religion 'RELIGIOUS AFFILIATION'
   evanprot 'EVANGELICAL PROTESTANTS'
   protdnom 'PROTESTANT DENOMINATION'
   edu "`LEVEL OF EDUCATION COMPLETED'"
   maristat "`MARITAL STATUS'"
   yngstat "`HAVE CHILDREN'"
   yng# "`NUMBER OF CHILDREN'"
   yng#edu "`NUMBER OF CHILDREN IN SCHOOL'"
   yngcol "`WILL CHILDREN GO TO COLLEGE'"
   ernr$ "`MOST IMP SOURCE OF INCOME'"
   zernrlin "`IMP INCOME-EARNER''S RELSHIP TO RESP'"
   empstat "`RESPONDENT''S EMPLOYMENT STATUS IN 84'"
   occu "`RESPONDENT''S OCCUPATION'"
   unemp "`RESPONDENT UNEMPLOYED IN 84'"
   umem "`RESPONDENT''S UNION MEMBERSHIP'"
   rempstat "`RELATIVE''S EMPLOYMENT STATUS IN 84'"
   roccu "`RELATIVE''S OCCUPATION'"
   runemp "`RELATIVE UNEMPLOYED IN 84'"
   rumem "`RELATIVE''S UNION MEMBERSHIP'"
   hempstat 'HEAD OF HOUSEHOLD EMPLOYMENT STATUS'
   hoccu 'HEAD OF HOUSEHOLD OCCUPATION'
   hunemp 'HEAD OF HOUSEHOLD UNEMPLOYED IN 84'
   humem "HEAD OF HOUSEHOLD'S UNION MEMBERSHIP"
   race "`RACIAL GROUP -- RGROUP1'"
   ethnicid 'ETHNIC IDENTIFICATION'
   asam 'ASIAN-AMERICAN GROUPS'
   hispid 'HISPANIC GROUP ID'
   zusp "`BIGGEST PROBLEM OF USA'"
   ifracep "`SPECIAL PROBLEMS OF RGROUP1'"
   zracep "`BIGGEST PROBLEM OF RGROUP1'"
   psolgov "`GOVT REQD TO SOLVE PROBLEM OF RGRP1'"
   pgovlev "`GOVT LEVEL TO SOLVE PROBLEM OF RGRP1'"
   zpsolgrp "`IF OTHER GRP TO SOLVE PROBLEM OF RGRP1'"
   ifgrp2 "`ANY OTHER GROUP OF ID OR RGROUP2'"
   zgrp2 "`OTHER GROUP OF ID OR RGROUP2'"
   zgrp2p "`BIGGEST PROBLEM OF RGROUP2'"
   p2solgov "`GOVT REQD TO SOLVE PROBLEM OF RGRP2'"
   p2govlev "`GOVT LEVEL TO SOLVE PROBLEM OF RGRP2'"
   zp2solgr "`IF OTHR GRP TO SOLVE PROBLEM OF RGRP2'"
   ifloluc "`GROUPS WITH FEWER OPPORTUNITIES'"
   zloluc1 "`GROUP WITH FEWER OPPORTUNITIES'"
   zloluc2 "`OTHER GROUP WITH FEWER OPPORTUNITIES'"
   zloluc3 "`OTHER GROUP WITH FEWER OPPORTUNITIES'"
   zloluc4 "`OTHER GROUP WITH FEWER OPPORTUNITIES'"
   ifhiluc "`GROUPS WITH MORE OPPORTUNITIES'"
   zhiluc1 "`GROUP WITH MORE OPPORTUNITIES'"
   zhiluc2 "`OTHER GROUP WITH MORE OPPORTUNITIES'"
   zhiluc3 "`GROUPS WITH MORE OPPORTUNITIES'"
   zhiluc4 "`GROUPS WITH MORE OPPORTUNITIES'"
   prej "`AMERICANS PREJUDICED TO RGROUP1'"
   zprejgrp "`PARTICULAR GROUP PREJUDICED TO RGROUP1'"
   selfprej "`PERSONAL EXPERIENCE OF DISCRIMINATION'"
   zsitprej "`SITUATION OF DISCRIMINATION'"
   futprej "`FUTURE AMOUNT OF PREJUDICE'"
   arms$ "`INCREASED MILITARY SPENDING'"
   era "`EQUAL RIGHTS AMENDMENT'"
   edutax "`TAX CREDIT FOR PAROCHIAL-PVT SCHOOL'"
   prayr "`PRAYER IN PUBLIC SCHOOL'"
   welfa$ "`INCREASED SPENDING ON WELFARE'"
   abort$ "`BAN FED SPENDING ON ABORTIONS'"
   nogun "`BAN HANDGUNS'"
   deathp "`DEATH PENALTY FOR MURDER'"
   amnesty "`AMNESTY FOR ILLEGAL IMMIGRATION'"
   empsanc "`USE OF EMPLOYER SANCTIONS'"
   bilinge "`BILINGUAL EDUCATION PROGRAMS'"
   bilingb "`BILINGUAL BALLOTS'"
   zabort "`VIEWS ON ABORTION'"
   zborn "`RESPONDENT''S COUNTRY OF BIRTH'"
   ifupama "`IF PARENTS BORN IN US'"
   zpaborn "`COUNTRY OF FATHER''S BIRTH'"
   zmaborn "`COUNTRY OF MOTHER''S BIRTH'"
   link "`SOCIAL LINKS WITH COUNTRY OF ORIGIN'"
   link$ "`MONEY SENT HOME TO CTRY OF ORIGIN'"
   setl "`INTENTION TO SETTLE IN US'"
   ifctzn "`IF US CITIZEN YET'"
   ustate "`STATE IN US WHERE RESPONDENT WAS BORN'"
   ucal "`GENERATION ENTERING CALIFORNIA'"
   ulink "`SOCIAL LINKS WITH STATE:ORIGIN IN US'"
   zlang "`PRIMARY NON-ENGLISH LANGUAGE'"
   votlang "`USED BALLOT OF OTHER LANGUAGE IN 1984'"
   homown "`HOME OWNER OR RENTER'"
   income "`INCOME LEVEL'"
   pvote "`PRESIDENTIAL VOTE CHOICE 84'"
   voteuse "`IMPORTANCE OF VOTING'"
   sex "`SEX OF RESPONDENT'"
   coop "`CO-OPERATION OF RESPONDENT'"
   info "`INFORMATION LEVEL OF RESPONDENT'"
   tru "`SINCERITY OF RESPONDENT'"
   imgen 'IMMIGRANT GENERATION'
   noneng 'NON-ENG PRIMARY LANG OR SPAN INTERVIEW'
   splang "`SPANISH LANGUAGE INTERVIEWS'"
   iflang "`PRIMARY LANG: NON-ENGLISH OR SPANISH'" .

VALUE LABELS
 blktract
     1 'HIGH PERCENTAGE BLACK'
     2 'LOW PERCENTAGE BLACK' /
 ethsmple
     1 'HISPANIC SURNAME'
     2 'ASIAN SURNAME'
     3 'KOREAN SUBSAMPLE'
     4 'OTHER' /
 votestat contri$ polisho poliwork polirali togrup yngstat ifracep ifgrp2 noneng iflang
     0 'DK/NA'
     1 'YES'
     2 'NO' /
 zregstat
     0 'DK/NA'
     1 'REGISTERED'
     2 'NOT REGISTERED' /
 zpartsta
     0 'INAP'
     1 'DEMOCRAT'
     2 'REPUBLICAN'
     3 'INDEPENDENT'
     4 'OTHER'
     8 'DK/NA' /
 partyid
     0 'DK/NA'
     1 'STRONG DEMOCRAT'
     2 'WEAK DEMOCRAT'
     3 'LEANING DEMOCRAT'
     4 'INDEPENDENT'
     5 'LEANING REPUBLICAN'
     6 'WEAK REPUBLICAN'
     7 'STRONG REPUBLICAN'
     8 'OTHER' /
 toeo tonews
     0 'DK/NA'
     1 'FREQUENTLY'
     2 'SELDOM'
     3 'NEVER' /
 yprob
     1 'NATIONAL SECURITY'
     2 'NUCLEAR WAR'
     5 'GOVT SPENDING'
     7 'CENTRAL AMERICA'
     9 'WORLD HUNGER'
     11 'INTL INCIDENT'
     12 'CRIME'
     13 'GANGS'
     14 'DRUGS'
     15 'NEIGHBORHOOD WATCH'
     16 'RELIGIOUS RALLY'
     17 'PROPERTY CONDITIONS'
     18 'ABORTION'
     20 'SCHOOL PROBS'
     21 'ROADS STREETS'
     22 'HOUSING'
     23 'RACIAL ETHNIC ISSUES'
     25 'ILLEGAL IMMIGRATION'
     26 'WOMENS RIGHTS'
     27 'UTILITY RATES'
     29 'TAXES'
     35 'SENIOR CITIZENS'
     37 'DUMPS ENVIRONMENT'
     38 'NUCLEAR REACTORS'
     41 'UNION RALLY'
     42 'PARKS'
     44 'RENT CONTROL'
     45 "'REDEVELOPMENT"
     46 'LIQUOR DRUNKENESS'
     47 'LITTER'
     48 'FED BUDGET CUTS'
     49 'GUN CONTROL'
     50 'VOTING REGISTRATION'
     51 'TEENAGERS'
     52 'HEALTH MED ISSUES'
     54 'EDUCATIONAL FUNDING'
     55 'TRAFFIC CONTROL'
     58 'AID TO DISABLED'
     59 'POVERTY HOMELESS'
     60 'GAY RIGHTS'
     61 'AGRICULTURE'
     62 'POLICE PROBLEMS'
     64 'BUSING'
     65 'COMMUNITY ACTIVITIES'
     66 'BATTERED WOMEN'
     67 'YOUTH PROGRAMS'
     68 'VIETNAM WAR'
     70 'CHILD ABUSE'
     71 'THE ARTS'
     73 'XRATED VIDEOS'
     74 'HALT CONSTRUCTION'
     75 'DISCRIMINATION'
     77 'THE INS'
     78 'COMM. COLLEGES'
     79 'ZONING'
     80 'HALFWAY HOUSE'
     81 'ANIMAL SHELTER'
     82 'RED CROSS'
     84 'BIG BROTHER'
     85 'WORKING CONDITIONS'
     86 'MISC NGHBRHOOD ISSUES'
     88 'MISC' /
 comprob
     0 'INAP'
     1 'CRIME'
     2 'MORAL VALUES'
     3 'EDUCATION'
     4 'TRANSIT, TRAFFIC'
     5 'HOUSING/RENT CONTROL'
     6 'ETHNIC, DOCUMENTA'
     7 'POVERTY, WELFARE'
     8 'POLLUTION, LITTER'
     9 'POLI ORGANISATION'
     10 'WORLD/NATIONL ISSUES'
     11 'MISCELLANEOUS'
     98 'DK/NA' /
 religion
     0 'DK/NA'
     1 'CATHOLIC'
     2 'JEWISH'
     3 'PROTESTANT'
     4 'CHRISTIAN:GENERAL'
     5 'BUDDHIST'
     6 'OTHER'
     7 'NONE' /
 evanprot
     0 'DK/NA'
     1 'EVANGELICAL'
     2 'NOT EVANGELICAL'
     3 'NOT PROTESTANT' /
 protdnom
     1 'PRESBYTERIAN'
     2 'LUTHERAN'
     3 'CONGREGATIONAL'
     4 'EPISCOPALIAN'
     5 'METHODIST'
     6 'BAPTIST'
     7 'SOUTHERN BAPTIST'
     8 'CHURCH OF GOD'
     9 'PENTECOSTAL'
     10 'AME'
     11 'CHURCH OF CHRIST'
     12 'SEVENTH DAY ADVENTIST'
     13 'MORMON LDS'
     14 'UNITARIAN'
     15 "JEHOVAH'S WITNESSES"
     16 'OTHER PROTESTANT'
     17 'PROT. IN GNERAL' /
 edu
     0 'DK/NA'
     1 '0-8 YEARS'
     2 'SOME HIGH SCHOOL'
     3 'HIGH SCHOOL GRAD'
     4 'SOME COLLEGE'
     5 'SOME TRAINING/TRADE'
     6 'COMPLETED COLLEGE'
     7 'GRADUATE WORK' /
 maristat
     0 'DK/NA'
     1 'SINGLE'
     2 'MARRIED'
     3 'DIVORCED'
     4 'WIDOWED'
     5 'LIVING TOGETHER'
     6 'OTHER' /
 yng#
     0 'INAP'
     1 '1 CHILD'
     2 '2 CHILDREN'
     3 '3 CHILDREN'
     4 '4 CHILDREN'
     5 '5 CHILDREN'
     6 'MORE THAN 5 CHILDREN'
     8 'DK/NA' /
 yng#edu
     0 'NO CHILDREN'
     1 '1 CHILD'
     2 '2 CHILDREN'
     3 '3 CHILDREN'
     4 '4 CHILDREN'
     5 '5 CHILDREN'
     6 'MORE THAN 5 CHILDREN'
     8 'DK/NA'
     9 'INAP' /
 yngcol
     0 'INAP'
     1 'WILL GO'
     2 "SOME WILL/SOME WON'T"
     3 "WON'T GO"
     8 'DK/NA' /
 ernr$
     0 'DK/NA'
     1 'RESPONDENT'
     2 'SOMEONE ELSE'
     3 'RESP & SOMEONE ELSE' /
 zernrlin
     0 'INAP'
     1 'PARENTS'
     2 'DAD/ FATHER'
     3 'MOTHER'
     4 'HUSBAND'
     5 'WIFE'
     6 'BROTHER'
     7 'SISTER'
     8 'SPOUSE'
     9 'COUSIN'
     10 'UNCLE'
     11 'AUNT'
     12 'GRANDFATHER'
     13 'GRANDMOTHER'
     14 'BOYFRIEND'
     15 'EX-HUSBAND'
     16 'PRIVATE'
     17 'STEPFATHER'
     18 'SON'
     19 'DAUGHTER'
     20 'SCHOOL'
     21 'FRIEND'
     22 'SON-IN-LAW'
     23 'FIANCE'
     24 'BROTHER-IN-LAW'
     26 'OTHER'
     98 'DK/NA' /
 empstat rempstat
     0 'INAP'
     1 'WORKING'
     2 'UNEMPLOYED/LAID OFF'
     3 'HOUSEWIFE'
     4 'STUDENT'
     5 'RETIRED'
     6 'OTHER'
     8 'DK/NA' /
 occu roccu
     0 'INAP'
     1 'PROF/TECHNICAL'
     2 'MANAGERIAL'
     3 'SALES'
     4 'CLERICAL'
     5 'CRAFTSMEN'
     6 'OPERATIVES'
     7 'SERVICE WORKER'
     8 'LABORER'
     9 'OTHER'
     10 'DK/NA' /
 unemp runemp selfprej ifupama link link$ ulink votlang
     0 'INAP'
     1 'YES'
     2 'NO'
     8 'DK/NA' /
 umem rumem
     0 'INAP'
     1 'UNION'
     2 "TEACHERS'ASSO"
     3 'NO'
     8 'DK/NA' /
 hempstat
     0 'DK/NA'
     1 'WORKING'
     2 'UNEMPLOYED/LAID OFF'
     3 'HOUSEWIFE'
     4 'STUDENT'
     5 'RETIRED'
     6 'OTHER' /
 hoccu
     0 'NOT IN LABOUR FORCE'
     1 'PROF/TECHNICAL'
     2 'MANAGERIAL'
     3 'SALES'
     4 'CLERICAL'
     5 'CRAFTSMEN'
     6 'OPERATIVES'
     7 'SERVICE WORKER'
     8 'LABORER'
     9 'OTHER' /
 hunemp
     0 'NOT IN LABOUR FORCE'
     1 'YES'
     2 'NO' /
 humem
     0 'DK/NA'
     1 'UNION'
     2 "TEACHERS'ASSO"
     3 'NO' /
 race
     0 'DK/NA'
     1 'WHITE'
     2 'BLACK'
     3 'ASIAN'
     4 'PACIFIC ISLANDER'
     5 'AMERICAN INDIAN'
     6 'OTHER' /
 natnlity
     1 'BLACK'
     2 'AMERICAN INDIAN'
     3 'MEXICAN'
     4 'FILIPINO'
     5 'CHINESE'
     6 'JAPANESE'
     7 'KOREAN'
     8 'VIETNAMESE'
     9 'INDIAN'
     11 'ISRAELI'
     12 'ARMENIAN'
     13 'PALESTINIAN'
     14 'ENGLISH'
     15 'IRISH'
     16 'SCOTTISH'
     18 'GERMAN'
     19 'FRENCH'
     20 'SWISS'
     21 'POLISH'
     23 'SWEDISH'
     24 'DUTCH'
     25 'ITALIAN'
     26 'PORTUGUESE'
     27 'SPANISH'
     28 'RUSSIAN'
     29 'RUMANIAN'
     30 'HUNGARIAN'
     31 'NORWEGIAN'
     32 'AUSTRIAN'
     34 'GREEK'
     35 'FINNISH'
     36 'YUGOSLAVIAN'
     37 'UKRAINIAN'
     38 'BALTIC'
     39 'MEDITERRANEAN'
     40 'SLOVAK'
     41 'SCANDINAVIAN'
     42 'EUROPEAN'
     43 'EASTERN EUROPEAN'
     44 'CANADIAN'
     45 'AUSTRALIAN'
     46 'SALVADORAN'
     48 'NICARAUGUAN'
     49 'GUATEMALAN'
     50 'PUERTO RICAN'
     51 'CUBAN'
     52 'COSTA RICAN'
     53 'JAMAICAN'
     54 'VENEZUELAN'
     55 'HONDURAN'
     56 'COLUMBIAN'
     57 'ARGENTINIAN'
     58 'ECUADORAN'
     61 'CENTRAL AMERICAN'
     63 'HISPANIC'
     65 'LEBANESE'
     66 'MOORISH'
     67 'CREOLE'
     68 'ETHIOPIAN'
     69 'EGYPTIAN'
     70 'PAKISTANI'
     71 'BENGALI'
     72 'LAOTIAN'
     73 'BURMESE'
     74 'INDONESIAN'
     75 'THAI'
     76 'FIJIAN'
     77 'HAWAIIAN'
     79 'CAMBODIAN'
     81 'GUAMANIAN'
     82 'ORIENTAL'
     84 'SOUTH AFRICAN'
     85 'AMERICAN'
     98 'NO ETHNIC/NAT ID' /
 ethnicid
     0 'DK/NA'
     1 'WHITE'
     2 'BLACK'
     3 'HISPANIC'
     4 'ASIAN-AMERICAN'
     5 'OTHER/W ASIAN/AM IND'
     6 'NOT ASCERTAINED' /
 asam
     0 'INAP'
     1 'FILIPINO'
     2 'CHINESE'
     3 'JAPANESE'
     4 'KOREAN'
     5 'VIETNAMESE'
     6 'OTHER ASIAN-AMERICAN' /
 hispid
     0 'INAP'
     1 'MEXICAN'
     2 'NON-MEXICAN'
     3 'UNSPECIFIED HISPANIC'
     4 'NON-HISPANIC' /
 zusp
     0 'DK/NA'
     1 'THREAT/NUCLEAR WAR'
     2 'ARMS RACE'
     3 'SOVIET/COMMI THREAT'
     4 'RELS W/ SOVIET UNION'
     5 'TOO MUCH DEF EXPENDI'
     6 'TOO LITTL DEF EXPEND'
     7 'WAR:C AMERICA'
     8 'WAR:MIDDLE EAST'
     9 'WORLD HUNGER'
     10 'IIIW LOAN DEFAULTS'
     11 'FGN AFFAIRS:GEN'
     12 'CRIME'
     13 'YOUTH GANGS'
     14 'DRUGS, ALCOHOLISM'
     15 'SELFISHNESS'
     16 'LACK:RELI/MORALITY'
     17 'TOO MUCH WELFARE'
     18 'ABORTION'
     19 'INTERF/RELI IN PA'
     20 'EDUCATION'
     21 'MASS TRANSIT'
     22 'HOUSING HOMELESSNESS'
     23 'RACE/ETH DISCRIMINA'
     24 'RACE RELATIONS'
     25 'ILLEGAL IMMIGRATION'
     26 'DISCRIMINA VS WOMEN'
     27 'HIGH COST OF LIVING'
     28 'INFLATION'
     29 'HIGH TAXES'
     30 'HIGH INTEREST RATES'
     31 'UNEMPLOYMENT'
     32 'LARGE GOVT DEFICIT'
     33 'TRADE, BAL/PAYMENTS'
     34 'PROTECTIONISM'
     35 'SSEC/MEDICARE'
     36 'ECO:GEN'
     37 'ENVIRONMENT/POLLU'
     38 'NUCLEAR POWR PLANTS'
     39 'UTILITY BANKRUPTCIS'
     40 'BIG BUSI/CORPS'
     41 'LABOR PROBLEMS'
     42 'REAGAN GOVT POLICY'
     43 'POVERTY INEQUALITY'
     44 'LOSS OF ETH. HERITAGE'
     45 'POLITICAL APATHY'
     46 'FAMILY RELATED'
     47 'LIBERALISM'
     48 'MEDICAL COSTS'
     50 'PROBS IN PHILLIPINES'
     51 'PROBS IN IRELAND'
     52 'WWII REPARATIONS'
     54 'PAY EQUALITY'
     55 'AIDS PROBS OF GAYS'
     97 'OTHER' /
 zracep zgrp2p
     0 'INAP'
     1 'THREAT/NUCLEAR WAR'
     2 'ARMS RACE'
     3 'SOVIET/COMMI THREAT'
     4 'RELS W/ SOVIET UNION'
     5 'TOO MUCH DEF EXPENDI'
     6 'TOO LITTL DEF EXPEND'
     7 'WAR:C AMERICA'
     8 'WAR:MIDDLE EAST'
     9 'WORLD HUNGER'
     10 'IIIW LOAN DEFAULTS'
     11 'FGN AFFAIRS:GEN'
     12 'CRIME'
     13 'YOUTH GANGS'
     14 'DRUGS, ALCOHOLISM'
     15 'SELFISHNESS'
     16 'LACK:RELI/MORALITY'
     17 'TOO MUCH WELFARE'
     18 'ABORTION'
     19 'INTERF/RELI IN PA'
     20 'EDUCATION'
     21 'MASS TRANSIT'
     22 'HOUSING HOMELESSNESS'
     23 'RACE/ETH DISCRIMINA'
     24 'RACE RELATIONS'
     25 'ILLEGAL IMMIGRATION'
     26 'DISCRIMINA VS WOMEN'
     27 'HIGH COST OF LIVING'
     28 'INFLATION'
     29 'HIGH TAXES'
     30 'HIGH INTEREST RATES'
     31 'UNEMPLOYMENT'
     32 'LARGE GOVT DEFICIT'
     33 'TRADE, BAL/PAYMENTS'
     34 'PROTECTIONISM'
     35 'SSEC/MEDICARE'
     36 'ECO:GEN'
     37 'ENVIRONMENT/POLLU'
     38 'NUCLEAR POWR PLANTS'
     39 'UTILITY BANKRUPTCIS'
     40 'BIG BUSI/CORPS'
     41 'LABOR PROBLEMS'
     42 'REAGAN GOVT POLICY'
     43 'POVERTY INEQUALITY'
     44 'LOSS OF ETH. HERITAGE'
     45 'POLITICAL APATHY'
     46 'FAMILY RELATED'
     47 'LIBERALISM'
     48 'MEDICAL COSTS'
     50 'PROBS IN PHILLIPINES'
     51 'PROBS IN IRELAND'
     52 'WWII REPARATIONS'
     54 'PAY EQUALITY'
     55 'AIDS PROBS OF GAYS'
     97 'OTHER'
     98 'DK/NA' /
 psolgov p2solgov
     0 'INAP'
     1 'NO GOVT ACTION REQD'
     2 'GOVT ACTION REQD'
     8 'DK/NA' /
 pgovlev p2govlev
     0 'INAP'
     1 'FED GOVT'
     2 'STATE GOVT'
     3 'LOCAL GOVT'
     4 'ALL LEVELS OF GOVT'
     5 'FED & STATE GOVTS'
     6 'STATE & LOCAL GOVTS'
     8 'DK/NA' /
 zpsolgrp zp2solgr
     0 'INAP'
     1 'PRIVATE BUSINESS'
     2 'GROUP WORK TOGETHER'
     3 'INDIVIDUALS'
     4 'SOMETHING ELSE'
     8 'DK/NA' /
 zgrp2
     0 'INAP'
     1 'MEN'
     2 'WOMEN'
     3 'BLACKS'
     4 'WHITES'
     5 'WHITE MEN'
     6 'WHITE WOMEN'
     7 'BLACK MEN'
     8 'BLACK WOMEN'
     9 'DISABLED'
     10 'BUSINESSMEN'
     11 'HOUSEWIVES'
     12 'UNION MEMBERS'
     13 'FARMERS'
     14 'IMMIGRANTS, REFUGEES'
     15 'TEACHERS'
     16 'STUDENTS'
     17 'TAXPAYERS'
     18 'HOMEOWNERS'
     19 'RETD PEOPLE:ELDERLY'
     20 'SOCSEC RECIPIENTS'
     21 'WELFARE RECIPIENTS'
     22 'UNEMPLOYED'
     23 'EMPLOYED'
     24 'WORKING WOMEN'
     25 'ASIAN AMERICANS'
     26 'MEXI-AMS/HISPANICS'
     27 'NON-ENG SPEAKERS'
     28 'CATHOLICS'
     29 'JEWS'
     30 'BORN-AGIN CHRISTNS'
     31 'RELI PEOPLE'
     32 'VETS'
     33 'ALCHOHOLICS'
     34 'HOMOSEXUALS'
     35 'CONSERVATIVES'
     36 'NUKEFREEZE MOVEMT'
     37 'ENVIRONMENTALISTS'
     38 'SINGLE PARENTS'
     39 'YUPPIES'
     40 'BABY-BOOM GENERA'
     41 'OTHER OCCUPA GRPS'
     42 'NO PARTICULAR GRP'
     43 'IRANIANS, ARABS'
     44 'MINORITIES'
     45 'AMERICAN INDIANS'
     46 'LOWER CLASS'
     47 'UPPER/MIDDLE CLASS'
     48 'POLI/OFFI PEOPLE'
     97 'OTHER'
     98 'DK/NA' /
 ifloluc ifhiluc
     0 'DK/NA'
     1 'YES'
     2 'MAYBE/DEPENDS'
     3 'NO' /
 zloluc1 zloluc2 zloluc3 zloluc4
     0 'INAP'
     1 'MEN'
     2 'WOMEN'
     3 'BLACKS'
     4 'WHITES'
     5 'WHITE MEN'
     6 'WHITE WOMEN'
     7 'BLACK MEN'
     8 'BLACK WOMEN'
     9 'DISABLED'
     10 'BUSINESSMEN'
     11 'HOUSEWIVES'
     12 'UNION MEMBERS'
     13 'FARMERS'
     14 'IMMIGRANTS, REFUGEES'
     15 'TEACHERS'
     16 'STUDENTS'
     17 'TAXPAYERS'
     18 'HOMEOWNERS'
     19 'RETD PEOPLE:ELDERLY'
     20 'SOCSEC RECIPIENTS'
     21 'WELFARE RECIPIENTS'
     22 'UNEMPLOYED'
     23 'EMPLOYED'
     24 'WORKING WOMEN'
     25 'ASIAN AMERICANS'
     26 'MEXI-AMS/HISPANICS'
     27 'NON-ENG SPEAKERS'
     28 'CATHOLICS'
     29 'JEWS'
     30 'BORN-AGIN CHRISTNS'
     31 'RELI PEOPLE'
     32 'VETS'
     33 'VIETNAM VETS'
     34 'LIBERALS'
     35 'CONSERVATIVES'
     36 'NUKEFREEZE MOVEMT'
     37 'ENVIRONMENTALISTS'
     38 'SINGLE PARENTS'
     39 'YUPPIES'
     40 'YOUNG PEOPLE'
     41 'OTHER OCCUPA GRPS'
     42 'NO PARTICULAR GRP'
     43 'IRANIANS, ARABS'
     44 'MINORITIES'
     45 'AMERICAN INDIANS'
     46 'LOWER CLASS'
     47 'UPPER/MIDDLE CLASS'
     48 'POLI/OFFI PEOPLE'
     97 'OTHER'
     98 'DK/NA' /
 zhiluc1 zhiluc2
     0 'INAP'
     1 'MEN'
     2 'WOMEN'
     3 'BLACKS'
     4 'WHITES'
     5 'WHITE MEN'
     6 'WHITE WOMEN'
     7 'BLACK MEN'
     8 'BLACK WOMEN'
     9 'DISABLED'
     10 'BUSINESSMEN'
     11 'HOUSEWIVES'
     12 'UNION MEMBERS'
     13 'FARMERS'
     14 'IMMIGRANTS, REFUGEES'
     15 'TEACHERS'
     16 'STUDENTS'
     17 'TAXPAYERS'
     18 'HOMEOWNERS'
     19 'RETD PEOPLE:ELDERLY'
     20 'SOCSEC RECIPIENTS'
     21 'WELFARE RECIPIENTS'
     22 'UNEMPLOYED'
     23 'EMPLOYED'
     24 'WORKING WOMEN'
     25 'ASIAN AMERICANS'
     26 'MEXI-AMS/HISPANICS'
     27 'NON-ENG SPEAKERS'
     28 'CATHOLICS'
     29 'JEWS'
     30 'BORN-AGIN CHRISTNS'
     31 'RELI PEOPLE'
     32 'VETS'
     33 'VIETNAM VETS'
     34 'LIBERALS'
     35 'CONSERVATIVES'
     36 'NUKEFREEZE MOVEMT'
     37 'ENVIRONMENTALISTS'
     38 'SINGLE PARENTS'
     39 'YUPPIES'
     40 'BABY-BOOM GENERA'
     41 'OTHER OCCUPA GRPS'
     42 'NO PARTICULAR GRP'
     43 'IRANIANS, ARABS'
     44 'MINORITIES'
     45 'AMERICAN INDIANS'
     46 'LOWER CLASS'
     47 'UPPER/MIDDLE CLASS'
     48 'POLI/OFFI PEOPLE'
     97 'OTHER'
     98 'DK/NA' /
 zhiluc3 zhiluc4
     0 'INAP'
     1 'MEN'
     2 'WOMEN'
     3 'BLACKS'
     4 'WHITES'
     5 'WHITE MEN'
     6 'WHITE WOMEN'
     7 'BLACK MEN'
     8 'BLACK WOMEN'
     9 'DISABLED'
     10 'BUSINESSMEN'
     11 'HOUSEWIVES'
     12 'UNION MEMBERS'
     13 'FARMERS'
     14 'IMMIGRANTS'
     15 'TEACHERS'
     16 'STUDENTS'
     17 'TAXPAYERS'
     18 'HOMEOWNERS'
     19 'RETD PEOPLE/ELDERLY'
     20 'SOC SEC RECIPIENTS'
     21 'WELFARE RECIPIENTS'
     22 'UNEMPLOYED'
     23 'EMPLOYED'
     24 'WORKING WOMEN'
     25 'ASIAN AMERICANS'
     26 'MEXI-AMS/HISPANICS'
     27 'NON-ENG SPEAKERS'
     28 'CATHOLICS'
     29 'JEWS'
     30 'BORN-AGIN CHRISTNS'
     31 'RELI PEOPLE'
     32 'VETS'
     33 'VIETNAM VETS'
     34 'LIBERALS'
     35 'CONSERVATIVES'
     36 'NUKEFREEZE MOVEMT'
     37 'ENVIRONMENTALISTS'
     38 'SINGLE PARENTS'
     39 'YUPPIES'
     40 'BABY-BOOM GENERA'
     41 'OTHER*'
     42 'NO PARTICU GROUP'
     45 'MINORITIES'
     57 'PUERTO RICANS'
     98 'DK/NA' /
 prej
     0 'INAP'
     1 'MOST ARE'
     2 'SOME ARE'
     3 'MOST ARE NOT'
     8 'DK/NA' /
 zprejgrp
     0 'INAP'
     1 'MEN'
     2 'WOMEN'
     3 'BLACKS'
     4 'WHITES'
     5 'WHITE MEN'
     6 'WHITE WOMEN'
     7 'BLACK MEN'
     8 'BLACK WOMEN'
     9 'DISABLED'
     10 'BUSINESSMEN'
     11 'HOUSEWIVES'
     12 'UNION MEMBERS'
     13 'FARMERS'
     14 'IMMIGRANTS, REFUGEES'
     15 'TEACHERS'
     16 'STUDENTS'
     17 'TAXPAYERS'
     18 'HOMEOWNERS'
     19 'RETD PEOPLE:ELDERLY'
     20 'SOCSEC RECIPIENTS'
     21 'WELFARE RECIPIENTS'
     22 'UNEMPLOYED'
     23 'EMPLOYED'
     24 'WORKING WOMEN'
     25 'ASIAN AMERICANS'
     26 'MEXI-AMS/HISPANICS'
     27 'NON-ENG SPEAKERS'
     28 'CATHOLICS'
     29 'JEWS'
     30 'BORN-AGIN CHRISTNS'
     31 'RELI PEOPLE'
     32 'VETS'
     33 'VIETNAM VETS'
     34 'LIBERALS'
     35 'CONSERVATIVES'
     36 'NUKEFREEZE MOVEMT'
     37 'ENVIRONMENTALISTS'
     38 'SINGLE PARENTS'
     39 'YUPPIES'
     40 'BABY-BOOM GENERA'
     41 'OTHER OCCUPA GRPS'
     42 'NO PARTICULAR GRP'
     43 'IRANIANS, ARABS'
     44 'MINORITIES'
     45 'AMERICAN INDIANS'
     46 'LOWER CLASS'
     47 'UPPER/MIDDLE CLASS'
     48 'POLI/OFFI PEOPLE'
     49 'KKK'
     50 'SOUTHERNERS'
     97 'OTHER'
     98 'DK/NA' /
 zsitprej
     0 'INAP'
     1 'GETTING A JOB'
     2 'GETTING INTO SCHOOL'
     3 'GETTIN HOUSE-APARTM'
     4 'SOCIAL SITUATION'
     5 'ALL THE ABOVE 1-4'
     6 'ON THE JOB'
     7 'REL:TO POLICE LAW'
     8 'DURING WAR:IN CAMPS'
     9 'IN SCHO0L/COLLEGE'
     10 'COMMERCIAL DEALINGS'
     97 'OTHER'
     98 'DK/NA' /
 futprej
     0 'INAP'
     1 'MORE PREJUDICED'
     2 "WON'T CHANGE MUCH"
     3 'LESS PREJUDICED'
     8 'DK/NA' /
 arms$ era edutax prayr welfa$ abort$ nogun deathp amnesty empsanc bilinge bilingb
     0 'DK/NA'
     1 'FAVOR'
     2 'OPPOSE'
     7 'NO OPINION' /
 zabort
     0 'DK/NA'
     1 'SHD NEVER BE PERMTD'
     2 'ONLY IF RAPE/INCEST'
     3 "ALWAYS ONE'S CHOICE"
     4 'OTHER OPINION' /
 zborn
     0 'DK/NA'
     1 'U.S.'
     2 'MEXICO'
     3 'PILIPPINES'
     4 'CHINA'
     5 'TAIWAN'
     6 'HONG KONG'
     7 'JAPAN'
     8 'KOREA'
     9 'VIETNAM'
     10 'IRAN'
     11 'ISRAEL'
     12 'AFRICA'
     13 'EUROPE'
     14 'LATIN/C AMERICA'
     15 'ASIA'
     16 'WEST ASIA'
     17 'EL SALVADOR'
     97 'OTHER' /
 zpaborn zmaborn
     0 'INAP'
     1 'U.S.'
     2 'MEXICO'
     3 'PILIPPINES'
     4 'CHINA'
     5 'TAIWAN'
     6 'HONG KONG'
     7 'JAPAN'
     8 'KOREA'
     9 'VIETNAM'
     10 'IRAN'
     11 'ISRAEL'
     12 'AFRICA'
     13 'EUROPE/WHITE SETTLER'
     14 'LATIN/C AMERICA'
     15 'ASIA'
     16 'WEST ASIA'
     97 'OTHER'
     98 'DK/NA' /
 setl
     0 'INAP'
     1 'MIGHT GO BACK'
     2 'WILL STAY IN U.S.'
     8 'DK/NA' /
 ifctzn
     0 'INAP'
     1 'CITIZEN'
     2 'NOT CITIZEN'
     8 'DK/NA' /
 ucal
     0 'INAP'
     1 'PARENTS'
     2 'GRANDPARENTS'
     3 'BEFORE THAT'
     8 'DK/NA' /
 zlang
     0 'INAP'
     1 'SPANISH'
     2 'ITALIAN'
     3 'GREEK'
     4 'FRENCH'
     5 'GERMAN'
     6 'HEBREW'
     7 'ARABIC'
     8 'FARSI'
     9 'ARMENIAN'
     10 'HINDI'
     11 'JAPANESE'
     12 'CHINESE'
     13 'KOREAN'
     14 'VIETNAMESE'
     15 'TAGALOG'
     16 'THAI'
     17 ' PILIPINO'
     97 'OTHER'
     98 'DK/NA' /
 homown
     0 'DK/NA'
     1 'OWN'
     2 'RENT/DO NOT OWN' /
 income
     0 'DK/NA'
     1 'LESS THAN $10,000'
     2 '$10,000-15,000'
     3 '$15,000-20,000'
     4 '$20,000-25,000'
     5 '$25,000-30,000'
     6 '$30,000-40,000'
     7 '$40,000-60,000'
     8 'OVER $60,000' /
 pvote
     0 'INAP'
     1 'MONDALE'
     2 'REAGAN'
     3 'OTHER'
     8 'DK/NA' /
 voteuse
     0 'DK/NA'
     1 'NOT IMPORTANT'
     2 'IMP IF INTEREST AFF'
     3 'IMPORTANT' /
 sex
     1 'MALE'
     2 'FEMALE' /
 coop
     1 'VERY GOOD'
     2 'GOOD'
     3 'FAIR'
     4 'POOR'
     5 'VERY POOR' /
 info
     1 'VERY HIGH'
     2 'FAIRLY HIGH'
     3 'AVERAGE'
     4 'FAIRLY LOW'
     5 'VERY LOW' /
 tru
     1 'COMPLETELY SINCERE'
     2 'USUALLY SINCERE'
     3 'PERHAPS INSINCERE' /
 imgen
     0 'DK/NA'
     1 'NON-US BORN'
     2 'NON-US BORN PARENTS'
     3 'US-BORN PARENTS' /
 splang
     1 'ENG LANG INTERVIEWS'
     2 'SPAN LANG INTERVIEWS' / .

/* User Missing Value Specifications */
MISSING VALUES
  votestat (0)             zregstat (0)             zpartsta (0, 8)        
  contri$ (0)              polisho (0)              poliwork (0)           
  polirali (0)             partyid (0)              toeo (0)               
  tonews (0)               togrup (0)               yprob (0)              
  comprob (0, 98)          religion (0)             evanprot (0)           
  protdnom (0)             edu (0)                  maristat (0)           
  yngstat (0)              yng# (0, 8)              yng#edu (9, 8)         
  yngcol (0, 8)            ernr$ (0)                zernrlin (0, 98)       
  empstat (0, 8)           occu (0, 10)             unemp (0, 8)           
  umem (0, 8)              rempstat (0, 8)          roccu (0, 10)          
  runemp (0, 8)            rumem (0, 8)             hempstat (0)           
  hoccu (0)                hunemp (0)               humem (0)              
  race (0)                 natnlity (98, 99)        ethnicid (0)           
  asam (0)                 hispid (0)               zusp (0)               
  ifracep (0)              zracep (0, 98)           psolgov (0, 8)         
  pgovlev (0, 8)           zpsolgrp (0, 8)          ifgrp2 (0)             
  zgrp2 (0, 98)            zgrp2p (0, 98)           p2solgov (0, 8)        
  p2govlev (0, 8)          zp2solgr (0, 8)          ifloluc (0)            
  zloluc1 (0, 98)          zloluc2 (0, 98)          zloluc3 (0, 98)        
  zloluc4 (0, 98)          ifhiluc (0)              zhiluc1 (0, 98)        
  zhiluc2 (0, 98)          zhiluc3 (0, 98)          zhiluc4 (0, 98)        
  prej (0, 8)              zprejgrp (0, 98)         selfprej (0, 8)        
  zsitprej (0, 98)         futprej (0, 8)           arms$ (0)              
  era (0)                  edutax (0)               prayr (0)              
  welfa$ (0)               abort$ (0)               nogun (0)              
  deathp (0)               amnesty (0)              empsanc (0)            
  bilinge (0)              bilingb (0)              zabort (0)             
  zborn (0)                ifupama (0, 8)           zpaborn (0, 98)        
  zmaborn (0, 98)          link (0, 8)              link$ (0, 8)           
  setl (0, 8)              yentry (100)             ifctzn (0, 8)          
  ustate ('ZZ')            ucal (0, 8)              ulink (0, 8)           
  zlang (0, 98)            votlang (0, 8)           yyrborn (100)          
  homown (0)               income (0)               pvote (0, 8)           
  voteuse (0)              imgen (0)                noneng (0)             
  iflang (0) .
         

SAVE OUTFILE='C:/work/DataversUploads/M163V1/CJUEXP.sav'.
